LMS Application/Pages/Assignments/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegisterPage.model;

namespace RegisterPage.Pages.Assignments
{
    public class CreateModel : PageModel
    {
        private readonly RegisterPage.Data.RegisterPageContext _context;

        public CreateModel(RegisterPage.Data.RegisterPageContext context)
        {
            _context = context;
        }

        [BindProperty]
        public int selectedClassID { get; set; } = default;
        public List<classes> GrabStudent { get; set; }
        public List<register> MatchStudent { get; set; }

        [BindProperty]
        public string SubmitType { get; set; }

        public IActionResult OnGet(int id)
        {
            var username = HttpContext.Session.GetString("Username");
            var user = _context.register.SingleOrDefault(u => u.username == username);
            selectedClassID = id;
            if (user == null)
            {
                return RedirectToPage("Index");
            }

            // Get the course name for the selected class
            var selectedClass = _context.classes.SingleOrDefault(c => c.Id == selectedClassID);
            if (selectedClass != null)
            {
                // Store the course name in ViewData
                ViewData["CourseName"] = selectedClass.courseName;
            }

            ViewData["classID"] = new SelectList(_context.classes, "Id", "courseName");

            return Page();
        }

        [BindProperty]
        public assignments Assignments { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            var username = HttpContext.Session.GetString("Username");
            var user = _context.register.SingleOrDefault(u => u.username == username);
            if (user == null)
            {
                return RedirectToPage("Index");
            }

            if (selectedClassID != null)
            {
                var selectedClass = await _context.classes.SingleOrDefaultAsync(c => c.Id == selectedClassID);
                if (selectedClass != null)
                {
                    Assignments.courseNum = int.Parse(selectedClass.courseNumber);
                    Assignments.classID = selectedClass.Id;
                    Assignments.Classes = selectedClass;
                    Assignments.submissionType = SubmitType;
                }
            }
            TryValidateModel(Assignments);

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.assignments.Add(Assignments);
            await _context.SaveChangesAsync();

            MatchStudent = _context.classes
            .Include(c => c.Users)
            .Where(c => c.Id == selectedClassID)
            .SelectMany(c => c.Users)
            .ToList();

            foreach (var student in MatchStudent)
            {
                var createNotification = new Notification
                {
                    classID = selectedClassID,
                    Message = $"{Assignments.title} has been assigned",
                    Timestamp = DateTime.Now,
                    fromUserID = user.Id,
                    toUserID = student.Id
                };
                _context.Notification.Add(createNotification);

                // Check if the student already has a Notifications list and add the notification to it
                if (student.Notifications == null)
                {
                    student.Notifications = new List<Notification>();
                }
                student.Notifications.Add(createNotification);
                await _context.SaveChangesAsync();
            }

            var routeVal = new { id = selectedClassID };

            return RedirectToPage("/Course", routeVal);
        }

    }
}

LMS Application/Pages/Assignments/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RegisterPage.model;

namespace RegisterPage.Pages.Assignments
{
    public class DeleteModel : PageModel
    {
        private readonly RegisterPage.Data.RegisterPageContext _context;

        public DeleteModel(RegisterPage.Data.RegisterPageContext context)
        {
            _context = context;
        }

        [BindProperty]
        public assignments Assignments { get; set; } = default!;
        public string CourseName { get; set; }


        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignments = await _context.assignments.FirstOrDefaultAsync(m => m.ID == id);

            if (assignments == null)
            {
                return NotFound();
            }
            else
            {
                Assignments = assignments;

                // Retrieve the courseName from the Classes table based on classID
                var course = await _context.classes
                    .FirstOrDefaultAsync(c => c.Id == assignments.classID);

                if (course != null)
                {
                    CourseName = course.courseName;
                }
            }
            return Page();
        }

        public object getRouteVal(int? cid, int? aid)
        {
            var routeVal = new { id = cid, assignid = aid};
            return routeVal;
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignments = await _context.assignments.FindAsync(id);
            if (assignments != null)
            {
                var course = await _context.classes
                    .FirstOrDefaultAsync(c => c.Id == assignments.classID);
                Assignments = assignments;
                _context.assignments.Remove(Assignments);
                await _context.SaveChangesAsync();
            }


            return RedirectToPage("/Course", getRouteVal(assignments.classID, id));
        }
    }
}

LMS Application/Pages/Assignments/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RegisterPage.model;

namespace RegisterPage.Pages.Assignments
{
    public class DetailsModel : PageModel
    {
        private readonly RegisterPage.Data.RegisterPageContext _context;

        public DetailsModel(RegisterPage.Data.RegisterPageContext context)
        {
            _context = context;
        }

        public assignments Assignments { get; set; } = default!;
        public string? Role { get; private set; }
        public string CourseName { get; set; }


        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignments = await _context.assignments.FirstOrDefaultAsync(m => m.ID == id);
            if (assignments == null)
            {
                return NotFound();
            }
            else
            {
                Assignments = assignments;

                // Retrieve the courseName from the Classes table based on classID
                var course = await _context.classes
                    .FirstOrDefaultAsync(c => c.Id == assignments.classID);

                if (course != null)
                {
                    CourseName = course.courseName;
                }

            }

            // Check if the role is already stored in the session
            Role = HttpContext.Session.GetString("UserRole");

            if (string.IsNullOrEmpty(Role))
            {
                // Get the logged-in user's username
                var username = HttpContext.Session.GetString("Username");

                if (username != null)
                {
                    // Retrieve the user's role from the database
                    var user = await _context.register
                        .FirstOrDefaultAsync(u => u.username == username);

                    if (user != null)
                    {
                        Role = user.role;

                        // Store the role in the session
                        HttpContext.Session.SetString("UserRole", Role);
                    }
                }
            }

            return Page();
        }
    }
}

LMS Application/Pages/Assignments/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegisterPage.Data;
using RegisterPage.model;

namespace RegisterPage.Pages.Assignments
{
    public class EditModel : PageModel
    {
        private readonly RegisterPage.Data.RegisterPageContext _context;

        public EditModel(RegisterPage.Data.RegisterPageContext context)
        {
            _context = context;
        }

        [BindProperty]
        public assignments Assignments { get; set; } = default!;

        [BindProperty]
        public int? selectedClassID { get; set; } = default;

        [BindProperty]
        public string SubmitType { get; set; }

        public async Task<IActionResult> OnGetAsync(int? assignmentid, int classid)
        {
            var username = HttpContext.Session.GetString("Username");
            var user = _context.register.SingleOrDefault(u => u.username == username);
            selectedClassID = classid;
            if (user == null)
            {
                return RedirectToPage("Index");
            }
            if (classid == null)
            {
                return NotFound();
            }
            
            var assignments =  await _context.assignments.FirstOrDefaultAsync(m => m.ID == assignmentid);
            if (assignments == null)
            {
                return NotFound();
            }
            Assignments = assignments;
           ViewData["classID"] = new SelectList(_context.classes, "Id", "courseName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            var username = HttpContext.Session.GetString("Username");
            var user = _context.register.SingleOrDefault(u => u.username == username);
            if (user == null)
            {
                return RedirectToPage("Index");
            }
            if (selectedClassID != null)
            {
                var selectedClass = _context.classes.SingleOrDefault(c => c.Id == selectedClassID);
                Assignments.courseNum = int.Parse(selectedClass.courseNumber);
                Assignments.classID = selectedClass.Id;
                Assignments.Classes = selectedClass;
                Assignments.submissionType = SubmitType;
            }
            TryValidateModel(Assignments);
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Assignments).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!assignmentsExists(Assignments.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            var routeVal = new { id = selectedClassID };

            return RedirectToPage("/Course", routeVal);
        }

        private bool assignmentsExists(int id)
        {
            return _context.assignments.Any(e => e.ID == id);
        }
    }
}

LMS Application/Pages/Submissions/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegisterPage.Data;
using RegisterPage.model;

namespace RegisterPage.Pages.Submissions
{
    public class EditModel : PageModel
    {
        private readonly RegisterPage.Data.RegisterPageContext _context;

        public EditModel(RegisterPage.Data.RegisterPageContext context)
        {
            _context = context;
        }

        public string FileContent { get; set; }

        [BindProperty]
        public Submission Submission { get; set; } = default!;

        public register user { get; set; } = default!;

        public assignments assignment { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submission =  await _context.Submission.FirstOrDefaultAsync(m => m.ID == id);
            if (submission == null)
            {
                return NotFound();
            }
            Submission = submission;

            // For loading user information
            var User = await _context.register.FirstOrDefaultAsync(x => x.Id == Submission.UserID);
            user = User;

            // For loading assignment information
            var Assignment = await _context.assignments.FirstOrDefaultAsync(x => x.ID == Submission.AssignmentID);
            assignment = Assignment;

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Resources", "Submissions", Submission.file);

            if (filePath != null)
            {
                FileContent = await System.IO.File.ReadAllTextAsync(filePath);
            }

            ViewData["AssignmentID"] = new SelectList(_context.assignments, "ID", "description");
            ViewData["UserID"] = new SelectList(_context.register, "Id", "firstname");
            
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Assignment = await _context.assignments.FirstOrDefaultAsync(x => x.ID == Submission.AssignmentID);
            var retrieveClass = await _context.classes.SingleOrDefaultAsync(x => x.Id == Assignment.classID);
            var student = await _context.register.SingleOrDefaultAsync(x => x.Id == Submission.UserID);

            // Create a new notification
            var createNotification = new Notification
            {
                classID = retrieveClass.Id,
                Message = $"{Assignment.title} has been graded.",
                Timestamp = DateTime.Now,
                fromUserID = retrieveClass.professorID, // ID of the professor sending the notification
                toUserID = student.Id // ID of the student receiving the notification
            };

            _context.Notification.Add(createNotification);

            // Check if the student already has a Notifications list and add the notification to it
            if (student.Notifications == null)
            {
                student.Notifications = new List<Notification>();
            }
            student.Notifications.Add(createNotification);

            _context.Attach(Submission).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SubmissionExists(Submission.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index", new { id = Submission.AssignmentID });
        }


        private bool SubmissionExists(int id)
        {
            return _context.Submission.Any(e => e.ID == id);
        }

		public async Task<IActionResult> OnGetDownloadFileAsync(int id)
		{
			var submission = await _context.Submission.FirstOrDefaultAsync(m => m.ID == id);
			if (submission == null)
			{
				return NotFound();
			}

			Submission = submission;

			var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Resources", "Submissions", Submission.file);

			if (!System.IO.File.Exists(filePath))
			{
				return NotFound(); // Return a 404 if the file does not exist
			}

			// Get the file extension to determine the content type (MIME type)
			var fileExtension = Path.GetExtension(filePath).ToLower();
			string contentType = "";

			// Set MIME type based on file extension (you may add more types if needed)
			switch (fileExtension)
			{
				case ".jpg":
				case ".jpeg":
					contentType = "image/jpeg";
					break;
				case ".png":
					contentType = "image/png";
					break;
				case ".pdf":
					contentType = "application/pdf";
					break;
                case ".docx":
                    contentType = "document/docx";
                    break;
			}

			var fileName = Submission.file; // The name that will be given to the file when downloaded

			// Use PhysicalFile to return the file from the server
			return PhysicalFile(filePath, contentType, fileName);
		}
	}
}

LMS Application/Pages/Submissions/Create.cshtml
@page
@model RegisterPage.Pages.Submissions.CreateModel

@{
    ViewData["Title"] = "Create";
}

<!--Only Displays Teachers Nav-->
<style>
	.StudentView{display: none;}
</style>

<h1>Create</h1>

<h4>Submission</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Submission.UserID" class="control-label"></label>
                <select asp-for="Submission.UserID" class ="form-control" asp-items="ViewBag.UserID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Submission.AssignmentID" class="control-label"></label>
                <select asp-for="Submission.AssignmentID" class ="form-control" asp-items="ViewBag.AssignmentID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Submission.grade" class="control-label"></label>
                <input asp-for="Submission.grade" class="form-control" />
                <span asp-validation-for="Submission.grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Submission.submitTime" class="control-label"></label>
                <input asp-for="Submission.submitTime" class="form-control" />
                <span asp-validation-for="Submission.submitTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Submission.file" class="control-label"></label>
                <input asp-for="Submission.file" class="form-control" />
                <span asp-validation-for="Submission.file" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMS Application/Pages/Submissions/Delete.cshtml
@page
@model RegisterPage.Pages.Submissions.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<!--Only Displays Teachers Nav-->
<style>
	.StudentView{display: none;}
</style>


<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Submission</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.User.firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.Assignment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.Assignment.description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.grade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.grade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.submitTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.submitTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.file)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.file)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Submission.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

LMS Application/Pages/Submissions/Details.cshtml
@page
@model RegisterPage.Pages.Submissions.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<!--Only Displays Teachers Nav-->
<style>
	.StudentView{display: none;}
</style>


<h1>Submission for @Model.assignment.title</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.user.firstname)
            @Html.DisplayFor(model => model.user.lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.grade)
        </dt>
        <dd class="col-sm-10">
            @if (@Model.Submission.grade == null)
            {
                <p>-/100</p>
            }
            else
            {
                <p>@Html.DisplayFor(model => model.Submission.grade)/@Model.assignment.maxGrade</p>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.submitTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.submitTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.file)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.file)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Submission.ID">Grade</a> |
    <a asp-page="./Index" asp-route-id="@Model.Submission.AssignmentID">Back to Submissions</a>
</div>

LMS Application/Pages/Submissions/Edit.cshtml
@page "{action?}"
@model RegisterPage.Pages.Submissions.EditModel

@{
    ViewData["Title"] = "Edit";
    var currentAction = RouteData.Values["action"]?.ToString() ?? "Assignment Details";

}

<!--Only Displays Teachers Nav-->
<style>
    .StudentView{display: none;}
</style>

<style>
    .StudentView {
        display: none;
    }
</style>

<!--Styling for this page-->
<style>
    .card {
        margin: 30px auto;
        width: 80%;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }

        .form-group label {
            font-weight: bold;
            margin-bottom: 8px;
            font-size: 1.1rem;
        }

    .input-group {
        margin-bottom: 1rem;
    }

    input.form-control, select.form-control {
        border-radius: 8px;
        border: 1px solid #ddd;
        padding: 10px;
    }
</style>

<!--external style sheet-->
<link rel="stylesheet" href="~/css/courseStyle.css" />

<!-- Breadcrumb Navigation -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="/dashboard">Home</a></li>
        <li class="breadcrumb-item">
            <a asp-page="/Course" asp-route-id="@Model.assignment.classID">
                @Model.assignment.courseNum
            </a>
        </li>
        <li class="breadcrumb-item">
            <a asp-page="./Index" asp-route-id="@Model.Submission.AssignmentID">
                @Model.assignment.title Submissions
            </a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Grade Submission
        </li>
    </ol>
</nav>

<div class="card">
    <h1 class="my-2 mb-4">Grade for @Model.assignment.title</h1>

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Submission.ID" />
                <input type="hidden" asp-for="Submission.UserID" />
                <input type="hidden" asp-for="Submission.AssignmentID" />
                <input type="hidden" asp-for="Submission.User" />
                <input type="hidden" asp-for="Submission.Assignment" />
                <input type="hidden" asp-for="Submission.submitTime" />
                <input type="hidden" asp-for="Submission.file" />
                <div class="form-group">
                    <label for="user-name" class="control-label">Submission For</label>
                    <p id="user-name" class="form-text" style="font-size: 24px;">
                        @Model.user.firstname @Model.user.lastname
                    </p>
                </div>

                <div class="form-group">
                    <label asp-for="Submission.grade" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="Submission.grade" class="form-control" />
                        <span class="input-group-text">out of @Model.assignment.maxGrade</span>
                    </div>
                    <span asp-validation-for="Submission.grade" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Submission.submitTime" class="control-label"></label>
                    <input readonly asp-for="Submission.submitTime" class="form-control" />
                </div>

                <div class="form-group">
                    <a asp-page="./Index" asp-route-id="@Model.Submission.AssignmentID">
                        <button type="submit" class="btn btn-custom btn-submit">
                            Update Grade
                        </button>
                    </a>
                </div>
            </form>

            @if (@Model.Submission.file.EndsWith(".txt"))
            {
                <h2 class="mt-3 text-center">Text Submission</h2>

                <form>
                    <textarea id="filecontent" rows="10" cols="50" readonly>@Model.FileContent</textarea>
                </form>
            }
            else
            {
                <h2 class="mt-3 text-center">Download File Submission</h2>

                <a asp-page-handler="DownloadFile" asp-route-id="@Model.Submission.ID">@Model.Submission.file</a>
            }

        </div>
    </div>
    <div class="d-flex justify-content-center my-5">
        <a class="btn btn-custom btn-edit" asp-page="./Index" asp-route-id="@Model.Submission.AssignmentID">Back to Submissions</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}